---
- name: Prepare ubuntu server
  hosts: webservers
  become: true
  vars:
    new_user: robot

  tasks:
    - name: Базовая подготовка Ubuntu Server
      become: true
      block:
        - name: Добавим запуск sudo без пароля
          ansible.builtin.lineinfile:
            path: /etc/sudoers
            state: present
            regexp: '^%sudo'
            line: '%sudo ALL=(ALL) NOPASSWD: ALL'
            validate: '/usr/sbin/visudo -cf %s'

        - name: Создадим нового пользователя
          ansible.builtin.user:
            name: "{{ new_user }}"
            state: present
            groups:
              - sudo
            append: true
            create_home: true

        - name: Добавит ssh-key авторизации для нового пользователя
          ansible.posix.authorized_key:
            user: "{{ new_user }}"
            state: present
            key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"

        - name: Запретить аутентификацию по паролю для пользователя root
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            state: present
            regexp: '^#?PermitRootLogin'
            line: 'PermitRootLogin prohibit-password'

    - name: Установка программного обеспечения
      become: true
      block:
        - name: Установка базовых утилит (curl, git, ufw, mc, jq)
          ansible.builtin.apt:
            package:
              - curl
              - git
              - ufw
              - mc
              - jq
            state: present
            update_cache: true

    - name: Установка Docker и всех его зависимостей
      become: true
      block:

        - name: Установка ca-certificates, gnupg
          ansible.builtin.apt:
            package:
              - ca-certificates
              - gnupg
            state: present
            update_cache: true

        - name: Добавление официального GPG key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Настройка репозитория
          ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu focal stable
            state: present
            filename: docker
            update_cache: true

        - name: Установка Docker Engine
          ansible.builtin.apt:
            package:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin

        - name: Проверяем, что docker-установлен корректно и запущен
          ansible.builtin.service:
            name: docker
            state: restarted
            enabled: true

        - name: Добавить пользователя в группу docker
          ansible.builtin.user:
            name: "{{ new_user }}"
            groups:
              docker
            append: true

        - name: Перезагрузка сервера
          ansible.builtin.reboot:

  roles:
    - nvm

  post_tasks:
    - name: Перезагрузка сервера
      ansible.builtin.reboot:
