version: '3.9'
services:
  typoteka.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "typoteka.notify.fakesmtp"
    hostname: "typoteka.notify.fakesmtp"
    ports:
      - "8025:8025"
      - "1085:8080"

  typoteka.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: typoteka.notify.rabbitmq

    ports:
      - '1088:15672'
      - '5672:5672'

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
